list: $/luismayta/resume/models/portafolio/columns.yaml
modelClass: LuisMayta\Resume\Models\Portafolio
title: Portafolio
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/resume/portafolio/update/:id'
