name: Portafolio
form: $/luismayta/resume/models/portafolio/fields.yaml
modelClass: LuisMayta\Resume\Models\Portafolio
defaultRedirect: luismayta/resume/portafolio
create:
    redirect: 'luismayta/resume/portafolio/update/:id'
    redirectClose: luismayta/resume/portafolio
update:
    redirect: luismayta/resume/portafolio
    redirectClose: luismayta/resume/portafolio
