list: $/luismayta/resume/models/habilidades/columns.yaml
modelClass: LuisMayta\Resume\Models\Habilidades
title: HabilidadesController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/resume/habilidadescontroller/update/:id'
