plugin:
    name: 'luismayta.resume::lang.plugin.name'
    description: 'luismayta.resume::lang.plugin.description'
    author: 'Luis Mayta'
    icon: oc-icon-graduation-cap
    homepage: ''
navigation:
    main-menu-item:
        label: Resume
        url: luismayta/resume/sitiocontroller
        icon: icon-graduation-cap
        sideMenu:
            side-menu-item:
                label: 'Datos personales'
                url: luismayta/resume/datospersonalescontroller
                icon: icon-user
