plugin:
    name: 'luismayta.resume::lang.plugin.name'
    description: 'luismayta.resume::lang.plugin.description'
    author: 'Luis Mayta'
    icon: oc-icon-graduation-cap
    homepage: ''
navigation:
    main-menu-item:
        label: Resume
        url: luismayta/resume/sitiocontroller/update/1
        icon: icon-graduation-cap
        sideMenu:
            side-menu-item:
                label: 'Datos personales'
                url: luismayta/resume/datospersonalescontroller/update/1
                icon: icon-user
            side-menu-item2:
                label: Experiencia
                url: luismayta/resume/experienciacontroller
                icon: icon-area-chart
            side-menu-item3:
                label: Educación
                url: luismayta/resume/educacioncontroller
                icon: icon-graduation-cap
            side-menu-item4:
                label: Habilidades
                url: luismayta/resume/habilidadescontroller
                icon: icon-angellist
            side-menu-item5:
                label: Idiomas
                url: luismayta/resume/idiomascontroller
                icon: icon-sort-alpha-asc
            side-menu-item6:
                label: Portafolio
                url: luismayta/resume/portafolio
                icon: icon-sitemap
