plugin:
    name: 'luismayta.resume::lang.plugin.name'
    description: 'luismayta.resume::lang.plugin.description'
    author: 'Luis Mayta'
    icon: oc-icon-graduation-cap
    homepage: ''
navigation:
    main-menu-item:
        label: 'My Cv'
        url: luismayta/resume/datospersonales
        icon: icon-graduation-cap
