name: DatosPersonales
form: $/luismayta/resume/models/datospersonales/fields.yaml
modelClass: LuisMayta\Resume\Models\DatosPersonales
defaultRedirect: luismayta/resume/datospersonales
create:
    redirect: 'luismayta/resume/datospersonales/update/:id'
    redirectClose: luismayta/resume/datospersonales
update:
    redirect: luismayta/resume/datospersonales
    redirectClose: luismayta/resume/datospersonales
