list: $/luismayta/resume/models/experiencia/columns.yaml
modelClass: LuisMayta\Resume\Models\Experiencia
title: ExperienciaController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/resume/experienciacontroller/update/:id'
