list: $/luismayta/resume/models/recomendaciones/columns.yaml
modelClass: LuisMayta\Resume\Models\Recomendaciones
title: RecomendacionesController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/resume/recomendacionescontroller/update/:id'
