fields:
    idioma:
        label: Idioma
        span: auto
        type: text
    bandera:
        label: Bandera
        options:
            ad: Andorra
            ae: Emiratos Árabes Unidos
            af: Afganistán
            ag: Antigua y Barbuda
            ai: Anguila
            al: Albania
            am: Armenia
            an: Antillas Neerlandesas
            ao: Angola
            aq: Antártida
            ar: Argentina
            as: Samoa Americana
            at: Austria
            au: Australia
            aw: Aruba
            ax: Islas Áland
            az: Azerbaiyán
            ba: Bosnia y Herzegovina
            bb: Barbados
            bd: Bangladesh
            be: Bélgica
            bf: Burkina Faso
            bg: Bulgaria
            bh: Bahréin
            bi: Burundi
            bj: Benin
            bl: San Bartolomé
            bm: Bermudas
            bn: Brunéi
            bo: Bolivia
            br: Brasil
            bs: Bahamas
            bt: Bhután
            bv: Isla Bouvet
            bw: Botsuana
            by: Belarús
            bz: Belice
            ca: Canadá
            cc: Islas Cocos
            cf: República Centro-Africana
            cg: Congo
            ch: Suiza
            ci: Costa de Marfil
            ck: Islas Cook
            cl: Chile
            cm: Camerún
            cn: China
            co: Colombia
            cr: Costa Rica
            cu: Cuba
            cv: Cabo Verde
            cx: Islas Christmas
            cy: Chipre
            cz: República Checa
            de: Alemania
            dj: Yibuti
            dk: Dinamarca
            dm: Domínica
            do: República Dominicana
            dz: Argel
            ec: Ecuador
            ee: Estonia
            eg: Egipto
            eh: Sahara Occidental
            er: Eritrea
            es: España
            et: Etiopía
            fi: Finlandia
            fj: Fiji
            fk: Islas Malvinas
            fm: Micronesia
            fo: Islas Faroe
            fr: Francia
            ga: Gabón
            gb: Reino Unido
            gd: Granada
            ge: Georgia
            gf: Guayana Francesa
            gg: Guernsey
            gh: Ghana
            gi: Gibraltar
            gl: Groenlandia
            gm: Gambia
            gn: Guinea
            gp: Guadalupe
            gq: Guinea Ecuatorial
            gr: Grecia
            gs: Georgia del Sur e Islas Sandwich del Sur
            gt: Guatemala
            gu: Guam
            gw: Guinea-Bissau
            gy: Guayana
            hk: Hong Kong
            hm: Islas Heard y McDonald
            hn: Honduras
            hr: Croacia
            ht: Haití
            hu: Hungría
            id: Indonesia
            ie: Irlanda
            il: Israel
            im: Isla de Man
            in: India
            io: Territorio Británico del Océano Índico
            iq: Irak
            ir: Irán
            is: Islandia
            it: Italia
            je: Jersey
            jm: Jamaica
            jo: Jordania
            jp: Japón
            ke: Kenia
            kg: Kirguistán
            kh: Camboya
            ki: Kiribati
            km: Comoros
            kn: San Cristóbal y Nieves
            kp: Corea del Norte
            kr: Corea del Sur
            kw: Kuwait
            ky: Islas Caimán
            kz: Kazajstán
            la: Laos
            lb: Líbano
            lc: Santa Lucía
            li: Liechtenstein
            lk: Sri Lanka
            lr: Liberia
            ls: Lesotho
            lt: Lituania
            lu: Luxemburgo
            lv: Letonia
            ly: Libia
            ma: Marruecos
            mc: Mónaco
            md: Moldova
            me: Montenegro
            mg: Madagascar
            mh: Islas Marshall
            mk: Macedonia
            ml: Mali
            mm: Myanmar
            mn: Mongolia
            mo: Macao
            mq: Martinica
            mr: Mauritania
            ms: Montserrat
            mt: Malta
            mu: Mauricio
            mv: Maldivas
            mw: Malawi
            mx: México
            my: Malasia
            mz: Mozambique
            na: Namibia
            nc: Nueva Caledonia
            ne: Níger
            nf: Islas Norkfolk
            ng: Nigeria
            ni: Nicaragua
            nl: Países Bajos
            no: Noruega
            np: Nepal
            nr: Nauru
            nu: Niue
            nz: Nueva Zelanda
            om: Omán
            pa: Panamá
            pe: Perú
            pf: Polinesia Francesa
            pg: Papúa Nueva Guinea
            ph: Filipinas
            pk: Pakistán
            pl: Polonia
            pm: San Pedro y Miquelón
            pn: Islas Pitcairn
            pr: Puerto Rico
            ps: Palestina
            pt: Portugal
            pw: Islas Palaos
            py: Paraguay
            qa: Qatar
            re: Reunión
            ro: Rumanía
            rs: Serbia y Montenegro
            ru: Rusia
            rw: Ruanda
            sa: Arabia Saudita
            sb: Islas Solomón
            sc: Seychelles
            sd: Sudán
            se: Suecia
            sg: Singapur
            sh: Santa Elena
            si: Eslovenia
            sj: Islas Svalbard y Jan Mayen
            sk: Eslovaquia
            sl: Sierra Leona
            sm: San Marino
            sn: Senegal
            so: Somalia
            sr: Surinam
            st: Santo Tomé y Príncipe
            sv: El Salvador
            sy: Siria
            sz: Suazilandia
            tc: Islas Turcas y Caicos
            td: Chad
            tf: Territorios Australes Franceses
            tg: Togo
            th: Tailandia
            th: Tanzania
            tj: Tayikistán
            tk: Tokelau
            tl: Timor-Leste
            tm: Turkmenistán
            tn: Túnez
            to: Tonga
            tr: Turquía
            tt: Trinidad y Tobago
            tv: Tuvalu
            tw: Taiwán
            ua: Ucrania
            ug: Uganda
            us: Estados Unidos de América
            uy: Uruguay
            uz: Uzbekistán
            va: Ciudad del Vaticano
            vc: San Vicente y las Granadinas
            ve: Venezuela
            vg: Islas Vírgenes Británicas
            vi: Islas Vírgenes de los Estados Unidos de América
            vn: Vietnam
            vu: Vanuatu
            wf: Wallis y Futuna
            ws: Samoa
            ye: Yemen
            yt: Mayotte
            za: Sudáfrica
        showSearch: true
        span: auto
        type: dropdown
    nivel:
        label: Nivel
        options:
            basico: Básico
            intermedio: Intermedio
            avanzado: Avanzado
        showSearch: true
        span: auto
        type: dropdown
