list: $/luismayta/resume/models/educacion/columns.yaml
modelClass: LuisMayta\Resume\Models\Educacion
title: EducacionController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/resume/educacioncontroller/update/:id'
