list: $/luismayta/resume/models/contacto/columns.yaml
modelClass: LuisMayta\Resume\Models\Contacto
title: ContactoController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/resume/contactocontroller/update/:id'
