list: $/luismayta/resume/models/datospersonales/columns.yaml
modelClass: LuisMayta\Resume\Models\DatosPersonales
title: DatosPersonalesController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/resume/datospersonalescontroller/update/:id'
