list: $/luismayta/resume/models/idiomas/columns.yaml
modelClass: LuisMayta\Resume\Models\Idiomas
title: IdiomasController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/resume/idiomascontroller/update/:id'
